name: turbostat_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.1.0
  dartz: ^0.10.0
  equatable: ^2.0.3
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^4.1.1
  get_it: ^7.2.0
  google_sign_in: ^5.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  meta: ^1.7.0
  nanoid: ^1.0.0
  path_provider: ^2.0.7
  provider: ^6.0.1
  shared_preferences: ^2.0.9

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.0.1
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - res/images/start_logo.png
    - res/images/google_logo.png
