// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIPOAGbydOZDZ5X0DhY47PmeNei1LsL_s',
    appId: '1:337246895110:android:8d16fd36b2ee9533f29787',
    messagingSenderId: '337246895110',
    projectId: 'carstat-d0da1',
    databaseURL: 'https://carstat-d0da1.firebaseio.com',
    storageBucket: 'carstat-d0da1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCtplCvokFQxOXakMzBk7Q7JQvWzW9jUs',
    appId: '1:337246895110:ios:e36571b183d09035f29787',
    messagingSenderId: '337246895110',
    projectId: 'carstat-d0da1',
    databaseURL: 'https://carstat-d0da1.firebaseio.com',
    storageBucket: 'carstat-d0da1.appspot.com',
    androidClientId: '337246895110-15ili658rdmui3doiu3e7d4oo14b9sas.apps.googleusercontent.com',
    iosClientId: '337246895110-ulfl44jv1d9vo952nkhtt4ouuqpegdfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.turbostatApp',
  );
}
